### ISSUE TITLE
Compiled .jar version to download

### ISSUE THREAD

**Issue by dklima** [TeknoServal/WorldWrapper#2]
Could you provide the .jar compiled ready to be downloaded?

I've found here [https://www.curseforge.com/minecraft/bukkit-plugins/worldwrapper/files](https://www.curseforge.com/minecraft/bukkit-plugins/worldwrapper/files), but it would be awesome if you also could provide a release tag here on GitHub too.

**Comment by RetynaGirl** [comment]
Check check, and done! checkout [here](https://github.com/TeknoServal/WorldWrapper/releases/tag/1.1.2) for some fun stuff!
